### PR TITLE
Upgrade to CRA 1.0.10

### PR DESCRIPTION
**Pull request by Grsmto**
Neverbland now maintains his own fork of Create React App: as advised by Dan [here](https://github.com/facebookincubator/create-react-app/issues/682), it's easier to fork and setup your own `react-scripts`. 
All the Webpack config that was previously in the Neverbuild is now externalised to [our fork](https://github.com/Neverbland/create-react-app/tree/master/packages/react-scripts).
This way Neverbuild will be easier to maintain.
Usage is the same as before, download/clone repo and follow install instructions.

### CODE REVIEW

**Comment by woffleloffle** [comment]
There's a whole bunch of stuff in `src/containers/shell.js` pertaining to a current client project in this commit. Perhaps just refactor some of that before we merge this?

**Comment by Grsmto** [comment]
Oops. Should be fixed.

**Comment by woffleloffle** [comment]
The tests `yarn test` fails with:

```bash
$ yarn test
yarn test v0.27.5
$ react-scripts test --env=jsdom
- Validation Error:

  Module ./node_modules/@neverbland/react-scripts/config/polyfills.js in the setupFiles option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

error Command failed with exit code 1.
```

Adding the `polyfills.js` file back into `@neverbland/create-react-app` fixes the issue.
I'll create a pull request in the other project. Once I've done that, we can close and merge this?

**Comment by Grsmto** [comment]
The file shouldn't be there as we don't use it and we use Polyfill.io instead. So instead of adding it back we should change the tests.
Thanks for this!

**Comment by woffleloffle** [comment]
Okay, cool. Would you do the necessary?
We can catch up about this tomorrow :)

**Pull request merged**
